### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by jdbs9514** [jdbs9514/javaScript-Group-Capstone#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by Kingstalux** [comment]
Hi @team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :x: 

- [ ] The issue you should submit for review should have a link to your GitHub project and also information on the number and names of the team members present. Kindly add this information before requesting for a review :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
